import Head from "next/head"
import Image from "next/image"

// Smart components
// import VercelButton from "https://framer.com/m/VercelButton-YAlC.js";
// import Hero from "https://framer.com/m/Carousel-K4xp.js"
// import Features from "https://framer.com/m/Features-RZDI.js"
import Features from "https://framer.com/m/Features-RZDI.js@VtnOh9SyPQjYJdUOpHaM"
import Hero from "https://framerusercontent.com/modules/oAIH4mJYirnv3yiamFCy/Ngp0r25dJiSrUBitTI8U/YWpZD78b2.js"
// Code component
// import Button from "https://framer.com/m/Button-7vAQ.js@9djRLPbFLMXwzcfFFyKm"

export default function Home() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
                <link
                    href="https://fonts.googleapis.com/css2?family=Nanum+Pen+Script&display=swap"
                    rel="stylesheet"
                />
            </Head>

            {/* <Hero width="100vw" /> */}
            <Features style={{ width: "100%" }} />
        </div>
    )
}
